services:
  composer:
    image: local/php:php-debian
    build:
      context: ./.docker/php
      target: php-debian
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: EDITME
      DATABASE_URL: "mysql://root:${MYSQL_PASSWORD:-sylius}@mysql/sylius_distroless_%kernel.environment%"
      MAILER_URL: smtp://mailhog:1025
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      - .:/var/www:rw,cached
      - ./public:/var/www/public:rw,delegated
      - public-media:/var/www/public/media:rw
    profiles:
      - composer

  php:
    image: local/php:php-distroless
    build:
      context: ./.docker/php
      target: php-distroless
    depends_on:
      - mysql
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: EDITME
      DATABASE_URL: "mysql://root:${MYSQL_PASSWORD:-sylius}@mysql/sylius_distroless_%kernel.environment%"
      MAILER_URL: smtp://mailhog:1025
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      - .:/var/www:rw,cached
      - ./public:/var/www/public:rw,delegated
      - public-media:/var/www/public/media:rw

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-sylius}
      - MYSQL_DATABASE=sylius
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-sylius}
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    cap_add:
      - SYS_NICE # prevent "mbind: Operation not permitted" errors
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW databases;\""
      interval: 5s
      timeout: 2s
      retries: 5

  nodejs:
    working_dir: /var/www
    image: "node:${NODE_VERSION:-16}-alpine"
    environment:
      GULP_ENV: dev
      PHP_HOST: php
      PHP_PORT: 9000
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        yarn install
        yarn build
    volumes:
      - .:/var/www:rw,cached
      - ./public:/var/www/public:rw,delegated
    ports:
      - "${NODE_PORT:-35729}:35729"
    profiles:
      - node

  nginx:
    build:
      context: ./.docker/nginx
    depends_on:
      - php
    volumes:
      - ./public:/var/www/public:ro
      - public-media:/var/www/public/media:ro,nocopy
    ports:
      - "${HTTP_PORT:-80}:80"

volumes:
  mysql-data:
  public-media:
